# General options  ------------------------------>
unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-a

# Custom options ------------------------------>
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-window on
set-option -g status-position top

# Bindings ------------------------------>
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

unbind %
unbind '"'
bind "'" split-window -h
bind ';' split-window

# Plugins ------------------------------>
set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'catppuccin/tmux'
set -g @plugin 'alexwforsythe/tmux-which-key'  # prefix + space

# Catppuccin --------------------------->

set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style "custom"

set -g @catppuccin_window_left_separator "#[bg=default,fg=#{@thm_surface_0}]#[bg=#{@thm_surface_0},fg=#{@thm_fg}]"
set -g @catppuccin_window_right_separator "#[bg=default,fg=#{@thm_surface_0}]"
set -g @catppuccin_window_current_left_separator "#[bg=default,fg=#{@thm_mauve}]#[bg=#{@thm_mauve},fg=#{@thm_bg}]"
set -g @catppuccin_window_current_middle_separator "#[fg=#{@thm_mauve}]█"
set -g @catppuccin_window_current_right_separator "#[bg=default,fg=#{@thm_surface_1}]"

set -g @catppuccin_status_background "none"

set -g status-right-length 100
set -g status-left-length 100
set -g status-left "#{?client_prefix,#[reverse]#[bold] >>>PREFIX #[noreverse] ,}"
set -g status-right "#{E:@catppuccin_status_directory}"
set -ag status-right "#{E:@catppuccin_status_session}"

# Tmux Navigator --------------------------->

# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
vim_pattern='(\S+/)?g?\.?(view|l?n?vim?x?|fzf)(diff)?(-wrapped)?'
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +${vim_pattern}$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'
tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'
if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\'  'select-pane -l'"
if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\\\'  'select-pane -l'"

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l

run '~/.tmux/plugins/tpm/tpm'
