link = !home/.dotfiles/.gitconfig !home/.gitconfig
link = !home/.dotfiles/.zshrc !home/.zshrc
link = !home/.dotfiles/.tmux.conf !home/.tmux.conf
link = !home/.dotfiles/.zephyrrc !home/.zephyrrc
link = !home/.dotfiles/starship.toml !xdg_conf/starship.toml
link = !home/.dotfiles/opencode !xdg_conf/opencode
link = !home/.dotfiles/hypr !xdg_conf/hypr
link = !home/.dotfiles/kitty !xdg_conf/kitty
link = !home/.dotfiles/nvim !xdg_conf/nvim
link = !home/.dotfiles/flameshot !xdg_conf/flameshot
link = !home/.dotfiles/quickshell !xdg_conf/quickshell
link = !home/.dotfiles/hamr !xdg_conf/hamr
link = !home/.dotfiles/qtengine !xdg_conf/qtengine
