link = !home/.dotfiles/misc/.gitconfig !home
link = !home/.dotfiles/misc/.tmux.conf !home

link = !home/.dotfiles/misc/starship.toml !xdg_conf
link = !home/.dotfiles/misc/electron-flags.conf !xdg_conf

link = !home/.dotfiles/.gnupg/gpg-agent.conf !home/.gnupg

link = !home/.dotfiles/zsh/.zshrc !xdg_conf/zsh/.zshrc
link = !home/.dotfiles/zsh/.zshenv !xdg_conf/zsh/.zshenv
link = !home/.dotfiles/zsh/shell/ !xdg_conf/shell

link = !home/.dotfiles/opencode !xdg_conf/opencode
link = !home/.dotfiles/hypr !xdg_conf/hypr
link = !home/.dotfiles/kitty !xdg_conf/kitty
link = !home/.dotfiles/nvim !xdg_conf/nvim
link = !home/.dotfiles/flameshot !xdg_conf/flameshot
link = !home/.dotfiles/quickshell !xdg_conf/quickshell
link = !home/.dotfiles/qtengine !xdg_conf/qtengine
link = !home/.dotfiles/matugen !xdg_conf/matugen
